version: "3"
services:
  changefinder:
    container_name: changefinder
    image: changefinder:1.0
    build:
      context: ./docker
      dockerfile: ./changefinder/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
